[tool.poetry]
name = "roarquery"
version = "0.1.5"
description = "Roarquery"
authors = ["Adam Richie-Halford <richiehalford@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/richford/roarquery"
repository = "https://github.com/richford/roarquery"
documentation = "https://roarquery.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
]

[tool.poetry.urls]
Changelog = "https://github.com/richford/roarquery/releases"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.1"
pandas = [
    { version = "<=1.3.5", python = "3.7" },
    { version = "^1.4.2", python = "3.8 || 3.9 || 3.10" }
]
python-dateutil = "^2.8.2"
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = {extras = ["toml"], version = "^6.3.3"}
safety = "^1.10.3"
mypy = "^0.950"
typeguard = "^2.13.2"
xdoctest = {extras = ["colors"], version = "^1.0.0"}
sphinx = "^4.3.0"
sphinx-autobuild = ">=2021.3.14"
pre-commit = "^2.15.0"
flake8 = "^4.0.1"
black = ">=21.10b0"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.4.25"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.1"
reorder-python-imports = "^3.1.0"
pre-commit-hooks = "^4.0.1"
sphinx-click = "^4.0.3"
Pygments = "^2.10.0"
pyupgrade = "^2.29.1"
furo = ">=2021.11.12"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"
types-python-dateutil = "^2.8.15"
pandas-stubs = "^1.2.0"

[tool.poetry.scripts]
roarquery = "roarquery.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["roarquery", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = [
    "tqdm.*",
    "pandas",
    "dateutil.parser"
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
